version: '3.8'
services:
  db:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - 9000:9000
      - 8123:8123
    env_file:
      - .env
    networks:
      - testnet
    volumes:
      - ./data_market:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
        test: ["CMD", "curl", "-f", "http://db:9000"]
        interval: 30s
        timeout: 10s
        retries: 5

  cluster_model:
    build: .
    container_name: cluster_spark
    env_file: 
      - .env
    volumes:
      - ./experiments:/experiments
      - ./data_market:/data_market
    command: /bin/bash -c '/opt/spark/bin/spark-submit ./src/loader.py && /opt/spark/bin/spark-submit ./src/clustering.py && /opt/spark/bin/spark-submit ./src/classifier.py'
    image: danjiii/cluster_spark
    networks:
      - testnet
    restart: on-failure

networks:
  testnet:
    driver: bridge